### PR TITLE
Fix spread attrs

### PR DESCRIPTION
**Pull request by s3bul**
Fix `TypeError: _vm.$attrs is not iterable`

### CODE REVIEW

**Comment by s3bul** [comment]
Zrzut ekranu z 2022-07-08 11-13-48


```
let test = {"one": "test one", "two": "test two"}
undefined
let test2 = [ ...test ]
Uncaught TypeError: test is not iterable
    <anonymous> debugger eval code:1

let test3 = { ...test }
undefined 
```

**Comment by yaminncco** [comment]
i'm getting an error
```
Uncaught Error: Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
```

**Comment by s3bul** [comment]
> i'm getting an error
> 
> ```
> Uncaught Error: Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
> ```

Hmm, maybe now?

**Comment by yaminncco** [comment]
You can just remove `...` its the same.

**Comment by s3bul** [comment]
> You can just remove `...` its the same.

`v-bind="[$attrs]"` this shallow copy `$attrs`?

Thanks for merge, now I waiting for publish new version :)

**Pull request merged**
