### PR TITLE
Allow specification of custom ID for the sidebar

### PR DESCRIPTION
**Pull request by LegendNed**
I currently have a top and bottoms sidebar, the bottom being in the footer of the top (main). Having an issue with the `id` system where ids get calculated weird as a result of using `id++` and causing this:
image

Where hovering over the bottom nav bar results in the top being opened. Would be lovely if it would be possible to add ID in the object of each route (NavbarMenuItem)

### CODE REVIEW

**Comment by yaminncco** [comment]
I think its better to add uniqueness to id instead of allowing for custom id
can you do it? i can make a fix

**Comment by LegendNed** [comment]
> I think its better to add uniqueness to id instead of allowing for custom id
> can you do it? i can make a fix

The problem is, having multiple side navigation bars causes the unique ids to overlap, shown in the gif bottom one opens top one (highlights), having an option to use unique I'd would be nice. If that makes sense

**Comment by yaminncco** [comment]
Yeah i understand the problem, what i meant is this can be fixed by creating unique id instead of using index

**Comment by LegendNed** [comment]
Correct, hence I've created a pull request, I can modify my pull request if one ID is detected, all routes must have an ID, as currently ID in the PR is only for any route/tab thing. Especially, having a hard coded one allowing to specify custom order :)

**Comment by yaminncco** [comment]
Fixed the issue in v5.2.1, appreciate your contribution.

**Pull request closed without merging**
