### PR TITLE
Allow non router urls in menu

### PR DESCRIPTION
**Pull request by moaddib666**
I've faced issue with remote urls for 3dparty MSS.
So I've add ability to use it by simple check if url exist in vue router.

### CODE REVIEW

**Comment by moaddib666** [comment]
> `this.$router.resolve({ path: this.item.href }).route.name !== true` so isRouterLink always return false and it doesn't work if href type is object
Hi @yaminncco, Thank you for updates.
I'm glad to see that project alive and under active development.
Indeed, my bad. I've adjusted the code in addition to your comment.

**Comment by yaminncco** [comment]
found issue when catch all Route is used in vue-router:

```
{
  path: '*',
  component: NotFound
}
```
so i am thinking about adding new property to support external links

**Comment by moaddib666** [comment]
Good point, if it acceptable from your side we could add new non required property named "external" with type: "bool"

And update mixins:

```
 isRouterLink () {
       return (this.$router && this.item && this.item.href !== undefined && !this.item.external) === true
     },
```

I've added new branch with mentioned changes.

**Comment by yaminncco** [comment]
added e5cee17a6389d677df166941bc7bceb22a600c77 thanks for contributing

**Pull request closed without merging**
